export const SESSION_STORAGE_SHARE_SHARE_KEY =
  "SESSION_STORAGE_SHARE_SHARE_KEY" as const;
export const SESSION_STORAGE_SHARE_REMOVAL_KEY =
  "SESSION_STORAGE_SHARE_REMOVAL_KEY" as const;
export const SESSION_STORAGE_SHARE_TRANSFER_KEY =
  "SESSION_STORAGE_SHARE_TRANSFER_KEY" as const;
